Inc3
mihailcoc/shortener pull request #10
Opened 2022-04-14 08:57 UTC by mihailcoc

2022-04-14 12:22 UTC, lugingf requested changes
Оставил комментарии

2022-04-14 12:22 UTC, lugingf commented on cmd/shortener/handler.go
> +		panic(err)
давай используем log.Fatal()

2022-04-14 12:22 UTC, lugingf commented on cmd/shortener/handler.go
> +	urls[mKey] = string(body)
Давай заведем структуру `Storage` для работы с условной БД

2022-04-14 12:22 UTC, lugingf commented on cmd/shortener/handler.go
> +	mKey := randomString(len(body) / 4)
Сейчас не критично, но в будущем пригодится - давай "бизнес логику" вынесем в отдельный слой `Service`

2022-04-14 12:27 UTC, lugingf commented on cmd/shortener/handler.go
> +		panic(err) // log fatal
log.Fatal()

2022-04-14 12:28 UTC, lugingf commented on cmd/shortener/handler.go
>  	g.String(http.StatusCreated, response)
Тут нужен Redirect

2022-04-14 20:31 UTC, lugingf commented on cmd/shortener/handler.go
> +	urls = make(map[string]string)
Еще я бы предложил вынести инициализацию БД в явном виде в `main`

2022-04-14 20:39 UTC, lugingf commented on cmd/shortener/handler.go
>  package main
Давай еще почистим ветку main и приберемся. 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/22412886/163471512-a601162f-cb7b-42e7-ae69-c7a20014e8f0.png">
Вот такая структура не очень норм. Для чего нам директория internal сейчас, например?

2022-04-15 12:46 UTC, mihailcoc commented
close pull

2022-04-15 13:03 UTC, merged

2022-04-15 13:03 UTC, mihailcoc commented
merged and closed